Fix error when the foreign field is overwrited by the relationship
mzalevski/postgrest-js-tools pull request #2
Opened 2022-07-10 09:35 UTC by jedymatt

- Added test case
- Fix error that overwrites the foreign field

2022-07-10 09:38 UTC, jedymatt commented
### Problem Before The Fix

Test case:
```typescript
test("foreign fields & relations", () => {
  const shape = getShape<Check>()({
    id: true,
    place_id: true,
    user_id: true,
    place: { _: "place_id", id: true, title: true },
    user: { _: "user_id", id: true, name: true },
  });

  const fields = getFields(shape);

  expect(fields).toBe("id,place_id,user_id,place:place_id(id,title),user:user_id(id,name)");
});
```


Error result

```typescript
Expected: "id,place_id,user_id,place:place_id(id,title),user:user_id(id,name)"
Received: "id,place:place_id_id,user:user_id_id,place:place_id(id,title),user:user_id(id,name)"
```

2022-07-11 16:36 UTC, mzalevski commented
I will look into it. Thanks.

2022-07-11 18:00 UTC, mzalevski requested changes

2022-07-11 18:00 UTC, mzalevski commented on index.test.ts
> +
you should also add a type test:
```typescript
  expectType<{
    id: string;
    place_id: string;
    user_id: string;
    place: { id: string; title: string };
    user: { id: string; name: string };
  }>(shape);
  ```

2022-07-11 18:00 UTC, mzalevski commented on src/index.ts
> +    // .replace(/\}/g, ")")
Leaving such comments is unnecessary. We can always check the previous version in git.

2022-07-11 18:00 UTC, mzalevski commented on src/index.ts
> +  }
This solution works, but there is a better one.

code to change on master:
```typescript
  if (Object.keys(joins).length > 0)
    return fields.replace(
      new RegExp(Object.keys(joins).join("|"), "g"),
      (m) => `${m}:${joins[m]}`
    );
```
another solution to the problem:
```typescript
  if (Object.keys(joins).length > 0)
    return fields.replace(
      new RegExp(Object.keys(joins).map((j) => `${j}(?=\\()`).join("|"), "g"),
      (m) => `${m}:${joins[m]}`
    );
```
as you can see, the only thing we need to fix the issue is a regex 'positive lookahead' on every join:
```
.map((j) => `${j}(?=\\()`)
```
the above means "match only if the next char is `(`"

the changes I'd like to see in this pull request look like [this](https://github.com/mzalevski/postgrest-js-tools/compare/master...the-foreign-field-is-overwritten-by-the-relationship)

2022-07-11 18:33 UTC, mzalevski approved these changes

2022-07-11 18:33 UTC, merged

2022-07-11 18:48 UTC, mzalevski commented
oh I forgot that the release is not triggered if there is no conventional commit prefix like in this case: fix. I will do some magic to make up for it. Anyway, thanks for help @jedymatt :)

2022-07-11 18:52 UTC, jedymatt commented
@mzalevski Thank you too for creating this awesome library as it can speed up my task. ヾ(≧▽≦*)o